### ISSUE TITLE
[Breaking Change] CUB-200-2011 is now hosted on Google Drive

### ISSUE THREAD

**Issue by dangpzanco** [lvyilin/pytorch-fgvc-dataset#1]
CUB-200-2011 is now hosted on Google Drive.

The [official link](http://www.vision.caltech.edu/visipedia-data/CUB-200-2011/CUB_200_2011.tgz) is the same, but it redirects to [this](https://drive.google.com/file/d/1hbzc_P1FuxMkcabkgn9ZKinBwW683j45).

A simple solution to this is to use `torchvision.utils.download_file_from_google_drive` instead of `torchvision.utils.download_url` and set the correct `file_id` (`1hbzc_P1FuxMkcabkgn9ZKinBwW683j45`).

**Comment by lvyilin** [comment]
Fixed. Thanks for your feedback!
